### ISSUE TITLE
Question of Firewall Template

### ISSUE THREAD

**Issue by mrc4tt** [GaetanOff/Firewall-Template#2]
Hi,

Really nice Firewall Template for OVH.
Sadly OVH doesn't provide or offer a setting to set up port ranges, when there are only 19 rules limits of Firewall.

Do you think, it's possible to block anything from the OVH Firewall and allow port ranges by iptables for example?

E.g.: 27000-28000, but that will need to be added into OVH-Firewall (which is not possible, due to 19 rules and no port-range support)

Is it just "game over" for the port range (s)?

**Comment by GaetanOff** [comment]
Hi,

Thanks for looking at Firewall. 😀
Yes, this is one of the limitations of network firewall, you cannot create a port range.

So if you need that many ports open on the Internet, you need to accept all requests.

Here is my discord, if you want to discuss it: gaetandev

**Comment by mrc4tt** [comment]
It's a shame that it's not possible to close everything and only open what is needed via iptables (TCP) / OVH Game Firewall (UDP)

So that everything is closed through the OVH Firewall so that limited ports can be opened via iptables and e.g. OVH GAME Firewall.

I will add you. My discord is miksen
